[package]
name = "espclient"
version = "1.0.5"
authors = ["Carlos A. Rueda <carueda@mbari.org>"]
edition = "2021"

[dependencies]
bytes = "1.2.1"

anstyle = "1.0" # for coloring clap help
clap = { version = "4.5", features = ["derive", "env"] }

colored = "3.0"
rustyline = "15.0"
