[package]
name = "espclient"
version = "1.0.1"
authors = ["Carlos A. Rueda <carueda@mbari.org>"]
edition = "2018"

[dependencies]
bytes = "1.1.0"
clap = { version = "3.2.22", features = ["derive"] }
colored = "2.0.0"
rustyline = "9.1.2"
