[package]
name = "espclient"
version = "1.0.2"
authors = ["Carlos A. Rueda <carueda@mbari.org>"]
edition = "2021"

[dependencies]
bytes = "1.2.1"
clap = { version = "3.2.23", features = ["derive"] }
colored = "2.0.0"
rustyline = "10.0.0"
