[package]
name = "espclient"
version = "1.0.0"
authors = ["Carlos A. Rueda <carueda@mbari.org>"]
edition = "2018"

[dependencies]
bytes = "1.1.0"
colored = "2.0.0"
structopt = "0.3.26"
rustyline = "9.1.2"
